### ISSUE TITLE
Given test dont execute and throws StateError

### ISSUE THREAD

**Issue by hu1buerger** [AndrewPiterov/given_when_then_unit_test#1]
When using the example (kinda; see the simple example with when then; aka the only example with Calculator) from pub.dev 
then the calculator isnt initialized and throws 

```dart
given("emtpy file", (){
    MemoryFileSystem mfs;
    late File file;

    print("rin");
      before((){
        print("before");
        mfs = MemoryFileSystem.test();
        file = mfs.file("/test.json");
      });

      when("storing a valid magician", () async {
        var store = FileMagician(file: file);

        assert(file.lengthSync() == 0);
        await file.doSomeAsync();

        then("the file should contain data", (){
            expect(file.lengthSync() > 0, isTrue);
        });
      });
  });
```

Running the test throws bcs before wasnt executed.

### I would expect:
that before gets called.

### Deps:

```
  given_when_then_unit_test: ^0.0.4
  file: ^6.1.2
  mocktail: 0.2.0
```

**Comment by hu1buerger** [comment]
After removing the before call and just calling both constructors,
the then case throws

```
StateError (Bad state: Can't call test() once tests have begun running.)
```

```
StackTrace.current
#0      Eval ()
#1      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:319:5)
#2      Declarer.test (package:test_api/src/backend/declarer.dart:164:5)
#3      test (package:test_core/scaffolding.dart:141:13)
#4      then (package:given_when_then_unit_test/res/then.dart:63:3)
#5      main.<anonymous closure>.<anonymous closure> (file:///test.dart)
<asynchronous suspension>
```

**Comment by hu1buerger** [comment]
Replacing 
```
Future<null> body = () async { /*no replication*/}; // body of  "when("storing a valid magician", body)" see above
when("storing magician", body);
//with
group("storing magician", body);
```
leads to `Declarer` from `test_api-0.4.2` in file `/lib/src/backend/declarer.dart` to throw an `ArgumentError('Groups may not be async.')` .

**Comment by hu1buerger** [comment]
This leads to the issue.

In this case when calls [body](https://github.com/AndrewPiterov/given_when_then_unit_test/blob/b2bb103b8edccdc95f3733c817ae43b8e8bd257e/lib/res/when.dart#L246) without regard that it might be a future.

In the initial code the test will not be registered against the declarer. Making matters worse the body passed to group will be synchronous and return null. 
`group` will be unable to detect the async body. [see](https://github.com/dart-lang/test/blob/767dbb5888ab5376ef0319006f7c90b028c1dbf8/pkgs/test_api/lib/src/backend/declarer.dart#L244)

I could imagine two paths. Either we check for async bodys and throw or add an async impl for when.

**Comment by AndrewPiterov** [comment]
> ```dart
> FileMagician
> ```

Hello @Hu1buerger ,
thanks for writing.

Could you please provide full code for this test? I cant find some class and method.

<img width="765" alt="2021-11-07_06-59-16" src="https://user-images.githubusercontent.com/10525569/140632981-864a0676-427a-4070-aebd-615120656512.png">
