### ISSUE TITLE
[FR] testmatrix

### ISSUE THREAD

**Issue by hu1buerger** [AndrewPiterov/given_when_then_unit_test#4]
When running the same test, just with different values.

Lets define a harness like

```dart
testcases([testcase1, ... , tcn], (testcase){
  
  given("test case with value", (){
    then("do some test", (){
      //should be ...
    });
  });
}};
```

This should be able to cleanup the test file, for given x cases do the same test.

Id love to hear feedback.

**Comment by AndrewPiterov** [comment]
Yes, great idea! it should be.

**Comment by hu1buerger** [comment]
Will do a PR
